# Site settings
author: Spencer Boucher
date_format: "%B %-d, %Y"
description:
email: spencer@spencerboucher.com
title: Spencer Boucher
url: "http://spencerboucher.com"

# Google services
google_analytics: UA-45101202-1
google_verification:

# Optional features
animated: true
show_related_posts: false
show_post_footers: true
show_social_icons: false
ajaxify_contact_form: true
enable_mathjax: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: justmytwospence

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: justmytwospence
bitbucket_username:
stackoverflow_id:
twitter_username: justmytwospence
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: spencerboucher
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text: 'Share this post!'
    facebook: 'Share on Facebook'
    twitter: 'Share on Twitter'
    googleplus: 'Share on Google+'
    linkedin: 'Share on LinkedIn'
    digg: 'Share on Digg'
    tumblr: 'Share on Tumblr'
    reddit: 'Share on Reddit'
    stumbleupon: 'Share on StumbleUpon'
    hackernews: 'Share on Hacker News'
  post:
    updated: 'Updated'
    minute_read: 'minute read'
    related_posts: 'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email: 'Email Address'
    content: 'What would you like to say?'
    subject: 'New submission!'
    submit: 'Contact'
    ajax:
      sending: 'sending..'
      sent: 'Message sent!'
      error: 'Error!'
  thanks: 'Thanks for contacting me. I will reply as soon as possible.'

# Build settings
destination: public
excerpt_separator: ""
exclude:
  - Gemfile*
  - Guardfile
  - LICENSE.txt
  - README.md
  - Rakefile
gems:
  - jekyll-paginate
  - jekyll-sitemap
markdown: redcarpet
paginate: 4
permalink: :title/
redcarpet:
  extensions:
    - autolink
    - footnotes
    - no_intra_emphasis
    - smart
    - tables
    - with_toc_data
sass:
  compressed: true
